server:
  port: 8761
   
  
#this below lines disable the wharehouse-registry-eureka from not being a client to itself 
eureka:
 instance:
   hostname: sa-warehouse-service-registry-SANDBOX.mymicroapps.net
 client:
   register-with-eureka: false
   fetch-registry: false
   serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
     
  
    
    
#Naming this spring-boot eureka server

spring:
  application:
    name:  WHAREHOUSE-EUREKA-SERVICE-REGISTRY
